# Generated by Django 6.0.3 on 2026-08-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_allow_missing_uploaded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleQuerySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
