# Generated by Django 6.0.3 on 2026-08-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articlequeryset'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
