"""
Django settings for CMS DB project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
import os
import socket
import sys
from pathlib import Path
from utils.strtbool import DistUtils
from dotenv import load_dotenv
from urllib.parse import urlparse

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
# Prefer explicit SECRET_KEY, fall back to DJANGO_SECRET_KEY (used by compose/.env)
SECRET_KEY = os.environ.get("SECRET_KEY") or os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(DistUtils.strtobool(os.getenv("DEBUG", "false")))

TESTING = ("test" in sys.argv) or any("pytest" in s for s in sys.argv) or os.environ.get("DJANGO_TESTING") == "1"

# https://docs.djangoproject.com/en/6.0/ref/settings/#std:setting-ALLOWED_HOSTS
allowed_hosts = os.getenv("ALLOWED_HOSTS", ".localhost,127.0.0.1,[::1]")
ALLOWED_HOSTS = list(map(str.strip, allowed_hosts.split(",")))

# Application definitions
INSTALLED_APPS = [
    "articles.apps.ArticlesConfig",
    "users.apps.UsersConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Determine whether the optional JWT auth backend is available. If it's not
# installed, fall back to an empty authentication list so imports don't fail.
_jwt_available = True
try:
    import importlib
    importlib.import_module("rest_framework_simplejwt")
except Exception:
    _jwt_available = False

if TESTING or not _jwt_available:
    REST_FRAMEWORK = {  # type: ignore
        "DEFAULT_AUTHENTICATION_CLASSES": [],
        "DEFAULT_THROTTLE_CLASSES": [],
        "DEFAULT_THROTTLE_RATES": {},
    }
else:
    REST_FRAMEWORK = {  # type: ignore
        "DEFAULT_AUTHENTICATION_CLASSES": [
            "rest_framework_simplejwt.authentication.JWTAuthentication",
        ],
        "DEFAULT_THROTTLE_CLASSES": [
            "rest_framework.throttling.AnonRateThrottle",
        ],
        "DEFAULT_THROTTLE_RATES": {
            "anon": "10/min",
        },
    }

    SIMPLE_JWT = {
        "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),
        "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    }

# Add whitenoise in non-testing environments only (avoid import during tests)
if not TESTING:
    if "whitenoise.middleware.WhiteNoiseMiddleware" not in MIDDLEWARE:
        MIDDLEWARE.insert(0, "whitenoise.middleware.WhiteNoiseMiddleware")

if DEBUG and not TESTING:
    if "debug_toolbar" not in INSTALLED_APPS:  # type: ignore
        INSTALLED_APPS.append("debug_toolbar")  # type: ignore
    if "debug_toolbar.middleware.DebugToolbarMiddleware" not in MIDDLEWARE:  # type: ignore
        MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")  # type: ignore

ROOT_URLCONF = "config.urls"

# Starting with Django 4.1+ we need to pick which template loaders to use
# based on our environment since 4.1+ will cache templates by default.
default_loaders = [
    "django.template.loaders.filesystem.Loader",
    "django.template.loaders.app_directories.Loader",
]

cached_loaders = [("django.template.loaders.cached.Loader", default_loaders)]

TEMPLATES = [ # type: ignore
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "loaders": default_loaders if DEBUG else cached_loaders,
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "cms_db"),
        "USER": os.getenv("POSTGRES_USER", "postgres"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "postgres-password"),
        "HOST": os.getenv("POSTGRES_HOST", "postgres"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}

# Optional Neon backup DB. If `NEON_URL` is present the project will expose a
# second database alias named `neon` that can be used for replica/backup
# writes (e.g. instance.save(using='neon')) or running migrations against
# the remote Neon cluster via `manage.py migrate --database=neon`.
NEON_URL = os.getenv("NEON_URL", "")
if NEON_URL:
    try:
        _u = urlparse(NEON_URL)
        DATABASES["neon"] = { # type: ignore
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _u.path.lstrip("/"),
            "USER": _u.username,
            "PASSWORD": _u.password,
            "HOST": _u.hostname,
            "PORT": _u.port or "",
            # Keep connections open for reuse; adjust as needed
            "CONN_MAX_AGE": 600,
            # Neon requires TLS; enforce sslmode unless explicitly included
            "OPTIONS": {"sslmode": "require"},
        }
    except Exception:
        # If parsing fails, don't crash startup — fall back to default only
        pass

# ADDED 2026-03-16 — Shared secret for the internal RAG corpus endpoint
# The FastAPI service sends this value in the X-RAG-Token header when fetching articles.
RAG_INTERNAL_TOKEN = os.getenv("RAG_INTERNAL_TOKEN", "")
# CHANGE LOG
# Changed by : Copilot
# Date       : 2026-03-16
# Reason     : Added RAG_INTERNAL_TOKEN so RagCorpusView can authenticate calls
#              from the FastAPI RAG ingestion service.
# Impact     : Must be set in the .env file and matched by CMS_RAG_TOKEN in the
#              FastAPI .env. If empty, RagCorpusView denies all requests.

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",  # noqa: E501
    },
]

# Sessions
# https://docs.djangoproject.com/en/6.0/ref/settings/#sessions
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

# Redis
REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")

# Caching
# https://docs.djangoproject.com/en/6.0/topics/cache/
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
    }
}

# Celery
# https://docs.celeryproject.org/en/stable/userguide/configuration.html
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = "/static/"
STATICFILES_DIRS = ["/public", os.path.join(BASE_DIR, "..", "public")]
STATIC_ROOT = "/public_collected"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
INTERNAL_IPS = ["127.0.0.1", "10.0.2.2"]
# Django Debug Toolbar
# https://django-debug-toolbar.readthedocs.io/
if DEBUG and not TESTING:
    # We need to configure an IP address to allow connections from, but in
    # Docker we can't use 127.0.0.1 since this runs in a container but we want
    # to access the toolbar from our browser outside of the container.
    try:
        hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
        new_ips = [ip[: ip.rfind(".")] + ".1" for ip in ips] + [
            "127.0.0.1",
            "10.0.2.2",
        ]
        INTERNAL_IPS[:] = new_ips
    except Exception:
        INTERNAL_IPS[:] = ["127.0.0.1", "10.0.2.2"]

INTERNAL_API_KEY = os.getenv("INTERNAL_API_KEY", "")